package javaapplication3;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Window 7
 */
public class number_to_words_converter extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public number_to_words_converter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 204), new java.awt.Color(204, 255, 204), new java.awt.Color(102, 255, 102), new java.awt.Color(153, 255, 51)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 153));
        jPanel1.setToolTipText("Enter the nuber to compute");

        jTextField1.setBackground(new java.awt.Color(0, 255, 255));

        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("<html><b><u><h3>Compute the numbers</b></u>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("Result of the given number");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setBackground(new java.awt.Color(255, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><center><h1><b>Number to Words converter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
            .addComponent(jLabel1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int t=0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int a=Integer.parseInt(jTextField1.getText());
String b=a+"";
int length=b.length();
String total=null;
if(length==1){
    char c=b.charAt(0);
    if(c=='0') total="zero";
    if(c=='1') total="one";
    if(c=='2') total="two";
    if(c=='3') total="three";
    if(c=='4') total="four";
    if(c=='5') total="five";
    if(c=='6') total="six";
    if(c=='7') total="seven";
    if(c=='8') total="eight";
    if(c=='9') total="nine";
}
if(length==2){
    
    if(b.equals("10")) total="ten";
    else if(b.equals("20")) total="twenty";
    else if(b.equals("30")) total="thirty";
    else if(b.equals("40")) total="fourty";
    else if(b.equals("50")) total="fifty";
    else if(b.equals("60")) total="sixty";
    else if(b.equals("70")) total="seventy";
    else if(b.equals("80")) total="eighty";
    else if(b.equals("90")) total="ninty";
    else if(b.equals("11")) total="eleven";
    else if(b.equals("12")) total="twelve";
    else if(b.equals("13")) total="thirteen";
    else if(b.equals("14")) total="fourteen";
    else if(b.equals("15")) total="fifteen";
    else if(b.equals("16")) total="sixteen";
    else if(b.equals("17")) total="seventeen";
    else if(b.equals("18")) total="eighteen";
    else if(b.equals("19")) total="ninteen";
    
    else{
        
        char c=b.charAt(0);
        
        if(c=='2') total="twenty";
        if(c=='3') total="thirty";
        if(c=='4') total="fourty";
        if(c=='5') total="fifty";
        if(c=='6') total="sixty";
        if(c=='7') total="seventy";
        if(c=='8') total="eightty";
        if(c=='9') total="ninty";
        ////space to write
        
        char d=b.charAt(1);
            
        if(d=='1') total=total+" one";
        if(d=='2') total=total+" two";
        if(d=='3') total=total+" three";
        if(d=='4') total=total+" four";
        if(d=='5') total=total+" five";
        if(d=='6') total=total+" six";
        if(d=='7') total=total+" seven";
        if(d=='8') total=total+" eight";
        if(d=='9') total=total+" nine";   
    }     
}
if(length==3){
    char c=b.charAt(0);
    if(c=='1') total="one hundred ";
    if(c=='2') total="two hundred ";
    if(c=='3') total="three hundred ";
    if(c=='4') total="four hundred ";
    if(c=='5') total="five hundred ";
    if(c=='6') total="six hundred ";
    if(c=='7') total="seven hundred ";
    if(c=='8') total="eight hundred ";
    if(c=='9') total="nine hundred ";
    
    b=b.charAt(1)+""+b.charAt(2);
    
    if(b.equals("10")) total=total+"ten";
    else if(b.equals("20")) total=total+"twenty";
    else if(b.equals("30")) total=total+"thirty";
    else if(b.equals("40")) total=total+"fourty";
    else if(b.equals("50")) total=total+"fifty";
    else if(b.equals("60")) total=total+"sixty";
    else if(b.equals("70")) total=total+"seventy";
    else if(b.equals("80")) total=total+"eighty";
    else if(b.equals("90")) total=total+"ninty";
    else if(b.equals("11")) total=total+"eleven";
    else if(b.equals("12")) total=total+"twelve";
    else if(b.equals("13")) total=total+"thirteen";
    else if(b.equals("14")) total=total+"fourteen";
    else if(b.equals("15")) total=total+"fifteen";
    else if(b.equals("16")) total=total+"sixteen";
    else if(b.equals("17")) total=total+"seventeen";
    else if(b.equals("18")) total=total+"eighteen";
    else if(b.equals("19")) total=total+"ninteen";
    
    else{
        
        c=b.charAt(0);
        
        if(c=='2') total=total+"twenty";
        if(c=='3') total=total+"thirty";
        if(c=='4') total=total+"fourty";
        if(c=='5') total=total+"fifty";
        if(c=='6') total=total+"sixty";
        if(c=='7') total=total+"seventy";
        if(c=='8') total=total+"eightty";
        if(c=='9') total=total+"ninty";
        ////space to write
        
        char d=b.charAt(1);
            
        if(d=='1') total=total+" one";
        if(d=='2') total=total+" two";
        if(d=='3') total=total+" three";
        if(d=='4') total=total+" four";
        if(d=='5') total=total+" five";
        if(d=='6') total=total+" six";
        if(d=='7') total=total+" seven";
        if(d=='8') total=total+" eight";
        if(d=='9') total=total+" nine";   
    }
    
}

if(length==4){
    char c=b.charAt(0);
    if(c=='1') total="one thousand ";
    if(c=='2') total="two thousand ";
    if(c=='3') total="three thousand ";
    if(c=='4') total="four thousand ";
    if(c=='5') total="five thousand ";
    if(c=='6') total="six thousand ";
    if(c=='7') total="seven thousand ";
    if(c=='8') total="eight thousand ";
    if(c=='9') total="nine thousand ";
    
    
    c=b.charAt(1);
    if(c=='1') total=total+"one hundred ";
    if(c=='2') total=total+"two hundred ";
    if(c=='3') total=total+"three hundred ";
    if(c=='4') total=total+"four hundred ";
    if(c=='5') total=total+"five hundred ";
    if(c=='6') total=total+"six hundred ";
    if(c=='7') total=total+"seven hundred ";
    if(c=='8') total=total+"eight hundred ";
    if(c=='9') total=total+"nine hundred ";
    
    b=b.charAt(2)+""+b.charAt(3);
    
    if(b.equals("10")) total=total+"ten";
    else if(b.equals("20")) total=total+"twenty";
    else if(b.equals("30")) total=total+"thirty";
    else if(b.equals("40")) total=total+"fourty";
    else if(b.equals("50")) total=total+"fifty";
    else if(b.equals("60")) total=total+"sixty";
    else if(b.equals("70")) total=total+"seventy";
    else if(b.equals("80")) total=total+"eighty";
    else if(b.equals("90")) total=total+"ninty";
    else if(b.equals("11")) total=total+"eleven";
    else if(b.equals("12")) total=total+"twelve";
    else if(b.equals("13")) total=total+"thirteen";
    else if(b.equals("14")) total=total+"fourteen";
    else if(b.equals("15")) total=total+"fifteen";
    else if(b.equals("16")) total=total+"sixteen";
    else if(b.equals("17")) total=total+"seventeen";
    else if(b.equals("18")) total=total+"eighteen";
    else if(b.equals("19")) total=total+"ninteen";
    
    else{
        
        c=b.charAt(0);
        
        if(c=='2') total=total+"twenty";
        if(c=='3') total=total+"thirty";
        if(c=='4') total=total+"fourty";
        if(c=='5') total=total+"fifty";
        if(c=='6') total=total+"sixty";
        if(c=='7') total=total+"seventy";
        if(c=='8') total=total+"eightty";
        if(c=='9') total=total+"ninty";
        ////space to write
        
        char d=b.charAt(1);
            
        if(d=='1') total=total+" one";
        if(d=='2') total=total+" two";
        if(d=='3') total=total+" three";
        if(d=='4') total=total+" four";
        if(d=='5') total=total+" five";
        if(d=='6') total=total+" six";
        if(d=='7') total=total+" seven";
        if(d=='8') total=total+" eight";
        if(d=='9') total=total+" nine";   
    }
    
}
String bc="";


if(length==5){
    bc=b.charAt(0)+""+b.charAt(1);
    if(bc.equals("10")) total="ten";
    else if(bc.equals("20")) total="twenty";
    else if(bc.equals("30")) total="thirty";
    else if(bc.equals("40")) total="fourty";
    else if(bc.equals("50")) total="fifty";
    else if(bc.equals("60")) total="sixty";
    else if(bc.equals("70")) total="seventy";
    else if(bc.equals("80")) total="eighty";
    else if(bc.equals("90")) total="ninty";
    else if(bc.equals("11")) total="eleven";
    else if(bc.equals("12")) total="twelve";
    else if(bc.equals("13")) total="thirteen";
    else if(bc.equals("14")) total="fourteen";
    else if(bc.equals("15")) total="fifteen";
    else if(bc.equals("16")) total="sixteen";
    else if(bc.equals("17")) total="seventeen";
    else if(bc.equals("18")) total="eighteen";
    else if(bc.equals("19")) total="ninteen";
    
    else{
        
        char c=bc.charAt(0);
        
        if(c=='2') total=total+"twenty";
        if(c=='3') total=total+"thirty";
        if(c=='4') total=total+"fourty";
        if(c=='5') total=total+"fifty";
        if(c=='6') total=total+"sixty";
        if(c=='7') total=total+"seventy";
        if(c=='8') total=total+"eightty";
        if(c=='9') total=total+"ninty";
        ////space to write
        
        char d=bc.charAt(1);
            
        if(d=='1') total=total+" one";
        if(d=='2') total=total+" two";
        if(d=='3') total=total+" three";
        if(d=='4') total=total+" four";
        if(d=='5') total=total+" five";
        if(d=='6') total=total+" six";
        if(d=='7') total=total+" seven";
        if(d=='8') total=total+" eight";
        if(d=='9') total=total+" nine";   
    }   
    total=total+" thousand ";
    
    char c=b.charAt(2);
    if(c=='1') total=total+"one hundred ";
    if(c=='2') total=total+"two hundred ";
    if(c=='3') total=total+"three hundred ";
    if(c=='4') total=total+"four hundred ";
    if(c=='5') total=total+"five hundred ";
    if(c=='6') total=total+"six hundred ";
    if(c=='7') total=total+"seven hundred ";
    if(c=='8') total=total+"eight hundred ";
    if(c=='9') total=total+"nine hundred ";
    
    b=b.charAt(3)+""+b.charAt(4);
    
    if(b.equals("10")) total=total+"ten";
    else if(b.equals("20")) total=total+"twenty";
    else if(b.equals("30")) total=total+"thirty";
    else if(b.equals("40")) total=total+"fourty";
    else if(b.equals("50")) total=total+"fifty";
    else if(b.equals("60")) total=total+"sixty";
    else if(b.equals("70")) total=total+"seventy";
    else if(b.equals("80")) total=total+"eighty";
    else if(b.equals("90")) total=total+"ninty";
    else if(b.equals("11")) total=total+"eleven";
    else if(b.equals("12")) total=total+"twelve";
    else if(b.equals("13")) total=total+"thirteen";
    else if(b.equals("14")) total=total+"fourteen";
    else if(b.equals("15")) total=total+"fifteen";
    else if(b.equals("16")) total=total+"sixteen";
    else if(b.equals("17")) total=total+"seventeen";
    else if(b.equals("18")) total=total+"eighteen";
    else if(b.equals("19")) total=total+"ninteen";
    
    else{
        
        c=b.charAt(0);
        
        if(c=='2') total=total+"twenty";
        if(c=='3') total=total+"thirty";
        if(c=='4') total=total+"fourty";
        if(c=='5') total=total+"fifty";
        if(c=='6') total=total+"sixty";
        if(c=='7') total=total+"seventy";
        if(c=='8') total=total+"eightty";
        if(c=='9') total=total+"ninty";
        ////space to write
        
        char d=b.charAt(1);
            
        if(d=='1') total=total+" one";
        if(d=='2') total=total+" two";
        if(d=='3') total=total+" three";
        if(d=='4') total=total+" four";
        if(d=='5') total=total+" five";
        if(d=='6') total=total+" six";
        if(d=='7') total=total+" seven";
        if(d=='8') total=total+" eight";
        if(d=='9') total=total+" nine";   
    }
}
////////////////////////////////////////////////////////////////////////////absolutely correct///////////////////////////////////////////////////
if(length==6){
    char c=b.charAt(0);
    if(c=='0') total="zero";
    if(c=='1') total="one";
    if(c=='2') total="two";
    if(c=='3') total="three";
    if(c=='4') total="four";
    if(c=='5') total="five";
    if(c=='6') total="six";
    if(c=='7') total="seven";
    if(c=='8') total="eight";
    if(c=='9') total="nine";
    
    total=total+" lakh ";
    
    if(b.charAt(1)==0){
        
    c=b.charAt(1);
    if(c=='1') total="one";
    if(c=='2') total="two";
    if(c=='3') total="three";
    if(c=='4') total="four";
    if(c=='5') total="five";
    if(c=='6') total="six";
    if(c=='7') total="seven";
    if(c=='8') total="eight";
    if(c=='9') total="nine";
    }
    else{
    bc=b.charAt(1)+""+b.charAt(2);
    if(bc.equals("10")) total=total+="ten";
    else if(bc.equals("20")) total=total+="twenty";
    else if(bc.equals("30")) total=total+="thirty";
    else if(bc.equals("40")) total=total+="fourty";
    else if(bc.equals("50")) total=total+="fifty";
    else if(bc.equals("60")) total=total+="sixty";
    else if(bc.equals("70")) total=total+="seventy";
    else if(bc.equals("80")) total=total+="eighty";
    else if(bc.equals("90")) total=total+="ninty";
    else if(bc.equals("11")) total=total+="eleven";
    else if(bc.equals("12")) total=total+="twelve";
    else if(bc.equals("13")) total=total+="thirteen";
    else if(bc.equals("14")) total=total+="fourteen";
    else if(bc.equals("15")) total=total+="fifteen";
    else if(bc.equals("16")) total=total+="sixteen";
    else if(bc.equals("17")) total=total+="seventeen";
    else if(bc.equals("18")) total=total+="eighteen";
    else if(bc.equals("19")) total=total+="ninteen";
    
    else{
        
        c=bc.charAt(0);
        
        if(c=='2') total=total+"twenty";
        if(c=='3') total=total+"thirty";
        if(c=='4') total=total+"fourty";
        if(c=='5') total=total+"fifty";
        if(c=='6') total=total+"sixty";
        if(c=='7') total=total+"seventy";
        if(c=='8') total=total+"eightty";
        if(c=='9') total=total+"ninty";
        ////space to write
        
        char d=bc.charAt(1);
            
        if(d=='1') total=total+" one";
        if(d=='2') total=total+" two";
        if(d=='3') total=total+" three";
        if(d=='4') total=total+" four";
        if(d=='5') total=total+" five";
        if(d=='6') total=total+" six";
        if(d=='7') total=total+" seven";
        if(d=='8') total=total+" eight";
        if(d=='9') total=total+" nine";   
    }   
    
    total=total+" thousand ";
    }
    
    
    c=b.charAt(3);
    if(c=='1') total=total+"one hundred ";
    if(c=='2') total=total+"two hundred ";
    if(c=='3') total=total+"three hundred ";
    if(c=='4') total=total+"four hundred ";
    if(c=='5') total=total+"five hundred ";
    if(c=='6') total=total+"six hundred ";
    if(c=='7') total=total+"seven hundred ";
    if(c=='8') total=total+"eight hundred ";
    if(c=='9') total=total+"nine hundred ";
    
    b=b.charAt(4)+""+b.charAt(5);
    
    if(b.equals("10")) total=total+"ten";
    else if(b.equals("20")) total=total+"twenty";
    else if(b.equals("30")) total=total+"thirty";
    else if(b.equals("40")) total=total+"fourty";
    else if(b.equals("50")) total=total+"fifty";
    else if(b.equals("60")) total=total+"sixty";
    else if(b.equals("70")) total=total+"seventy";
    else if(b.equals("80")) total=total+"eighty";
    else if(b.equals("90")) total=total+"ninty";
    else if(b.equals("11")) total=total+"eleven";
    else if(b.equals("12")) total=total+"twelve";
    else if(b.equals("13")) total=total+"thirteen";
    else if(b.equals("14")) total=total+"fourteen";
    else if(b.equals("15")) total=total+"fifteen";
    else if(b.equals("16")) total=total+"sixteen";
    else if(b.equals("17")) total=total+"seventeen";
    else if(b.equals("18")) total=total+"eighteen";
    else if(b.equals("19")) total=total+"ninteen";
    
    else{
        
        c=b.charAt(0);
        
        if(c=='2') total=total+"twenty";
        if(c=='3') total=total+"thirty";
        if(c=='4') total=total+"fourty";
        if(c=='5') total=total+"fifty";
        if(c=='6') total=total+"sixty";
        if(c=='7') total=total+"seventy";
        if(c=='8') total=total+"eightty";
        if(c=='9') total=total+"ninty";
        ////space to write
        
        char d=b.charAt(1);
            
        if(d=='1') total=total+" one";
        if(d=='2') total=total+" two";
        if(d=='3') total=total+" three";
        if(d=='4') total=total+" four";
        if(d=='5') total=total+" five";
        if(d=='6') total=total+" six";
        if(d=='7') total=total+" seven";
        if(d=='8') total=total+" eight";
        if(d=='9') total=total+" nine";   
    }
    
    
}



//System.out.println(total+"");
t++;
jTextArea1.append(t+". "+total+"\n");
jTextField1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(number_to_words_converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(number_to_words_converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(number_to_words_converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(number_to_words_converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new number_to_words_converter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}


/*
    #include <iostream>

using namespace std;

int main()
{
    int num,n1,n2,n3;
    cout<<"Enter the three digit number : ";
    cin>>num;
    n3=num%10;
    num=num/10;
    n2=num%10;
    num=num/10;
    n1=num%10;
    switch(n1)
    {
        case 0 : cout<<"";
                 break;
        case 1 : cout<<"One hundred ";
                 break;
        case 2 : cout<<"Two hundred ";
                 break;
        case 3 : cout<<"Three hundred ";
                 break;
        case 4 : cout<<"Four hundred ";
                 break;
        case 5 : cout<<"Five hundred ";
                 break;
        case 6 : cout<<"Six hundred ";
                 break;
        case 7 : cout<<"Seven hundred ";
                 break;
        case 8 : cout<<"Eight hundred ";
                 break;
        default : cout<<"Nine hundred ";
                  break;
    }
    if(n2==1)
    {
    switch(n3)
    {
        case 0 : cout<<"Ten";
                 break;
        case 1 : cout<<"Eleven";
                 break;
        case 2 : cout<<"Twelve";
                 break;
        case 3 : cout<<"Thirteen";
                 break;
        case 4 : cout<<"Fourteen";
                 break;
        case 5 : cout<<"Fifteen";
                 break;
        case 6 : cout<<"Sixteen";
                 break;
        case 7 : cout<<"Seventeen";
                 break;
        case 8 : cout<<"Eighteen";
                 break;
        default : cout<<"Nineteen";
                  break;
    }
    }
    else
    {
        switch(n2)
        {
        case 0 : cout<<"";
                 break;
        case 2 : cout<<"Twenty ";
                 break;
        case 3 : cout<<"Thirty ";
                 break;
        case 4 : cout<<"Forty ";
                 break;
        case 5 : cout<<"Fifty ";
                 break;
        case 6 : cout<<"Sixty ";
                 break;
        case 7 : cout<<"Seventy ";
                 break;
        case 8 : cout<<"Eighty ";
                 break;
        default : cout<<"Ninety ";
                  break;
        }
    switch(n3)
    {
        case 0 : cout<<"";
                 break;
        case 1 : cout<<"One";
                 break;
        case 2 : cout<<"Two";
                 break;
        case 3 : cout<<"Three";
                 break;
        case 4 : cout<<"Four";
                 break;
        case 5 : cout<<"Five";
                 break;
        case 6 : cout<<"Six";
                 break;
        case 7 : cout<<"Seven";
                 break;
        case 8 : cout<<"Eight";
                 break;
        default : cout<<"Nine";
                  break;
    }
    }
    return 0;
}


*/
